# Generated by Django 4.2.5 on 2023-09-20 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
                ('phone_number', models.IntegerField(verbose_name='Номер телефона')),
                ('message', models.TextField(max_length=1000, verbose_name='Сообщение')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('checked', models.BooleanField(default=False, verbose_name='Перезовнили')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адресс')),
                ('maps_link', models.URLField(blank=True, verbose_name='Ссылка на адресс')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp')),
                ('telegram', models.CharField(blank=True, max_length=30, verbose_name='Telegram')),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'Социальные сети',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='+996 (...) .. .. .. ', max_length=30, verbose_name='Номер')),
                ('contacts', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='main.contacts', verbose_name='Телефонные номера')),
            ],
        ),
    ]
