# Generated by Django 4.2.5 on 2023-09-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='message',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Сообщение'),
        ),
    ]
