# Generated by Django 4.2.5 on 2023-09-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_callback_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='message',
            field=models.TextField(max_length=1000, verbose_name='Сообщение'),
        ),
    ]
