# Generated by Django 4.2.5 on 2023-09-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_catalog_description_alter_item_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
