# Generated by Django 4.2.5 on 2023-09-20 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_catalog_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
                ('phone_number', models.IntegerField(verbose_name='Номер телефона')),
                ('message', models.TextField(max_length=1000, verbose_name='Сообщение')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('checked', models.BooleanField(default=False, verbose_name='Перезовнили')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'item'},
        ),
        migrations.AddField(
            model_name='catalog',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.catalog'),
        ),
        migrations.AlterField(
            model_name='itemfield',
            name='item',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='shop.item'),
        ),
        migrations.AlterField(
            model_name='itemfield',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Поле'),
        ),
        migrations.AlterField(
            model_name='itemfield',
            name='value',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='Значение'),
            preserve_default=False,
        ),
    ]
