# Generated by Django 4.2.5 on 2023-09-20 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_contacts_socialmedia_alter_catalog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='contacts',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='shop.contacts', verbose_name='Телефонные номера'),
        ),
    ]
