# Generated by Django 4.2.5 on 2023-09-20 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_phonenumber_contacts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CallBack',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='contacts',
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
