# Generated by Django 4.2.5 on 2023-09-22 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_delete_callback_remove_phonenumber_contacts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='catalog',
        ),
    ]
