# Generated by Django 4.2.5 on 2023-09-20 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_delete_callback_remove_phonenumber_contacts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='catalog',
        ),
        migrations.AlterField(
            model_name='catalog',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='image',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='itemfield',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='shop.item'),
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='shop.catalog')),
            ],
            options={
                'verbose_name': 'Парметр каталога товаров',
                'verbose_name_plural': 'Парметр каталога товаров',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='поле')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='shop.parameters')),
            ],
            options={
                'verbose_name': 'Название поля в таблице',
                'verbose_name_plural': 'Название поля в таблице',
            },
        ),
        migrations.AlterField(
            model_name='itemfield',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.field'),
        ),
    ]
