# Generated by Django 4.2.5 on 2023-09-20 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_category_item_catalog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemfield',
            name='title',
        ),
    ]
