# Generated by Django 4.2.5 on 2023-09-20 23:51

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_itemfield_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfield',
            name='title',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to=models.Q(('parameter__catalog', django.db.models.expressions.OuterRef('item__catalog'))), on_delete=django.db.models.deletion.CASCADE, to='shop.field'),
            preserve_default=False,
        ),
    ]
