# Generated by Django 4.2.5 on 2023-09-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_ourclientslogo_ourproviderslogo_catalog_price_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPriceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file_price', verbose_name='файл с ценами')),
            ],
            options={
                'verbose_name': 'Прайс лист на главной странице',
                'verbose_name_plural': 'Прайс лист на главной странице',
            },
        ),
    ]
