# Generated by Django 4.2.5 on 2023-09-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_itemfield_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='image',
            field=models.ImageField(upload_to='media', verbose_name='Изображение'),
        ),
    ]
